name = "Create: Ch4oS — New World"
author = "Cha0sCollective"
version = "0.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dcc05864d9a9ce57e297bdc6053c3ffd94b0f93daeef94f36b82741f05957a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = []
