name = "Create: Ch4oS — New World"
author = "Cha0sCollective"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04cf2b15dd6e9cb12aad7b85aec8c643373cfeabc26be7e67c3a8b6d7d1e795d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = []
