name = "Create: Ch4oS — New World"
author = "Cha0sCollective"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d01015a8565eca57cdc453c9baa29cee9d19865ca9ca1d00a62f8bcf50f212e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = []
